version: "2"
services:
  zookeeper:
    image: docker.confluent.io:5000/confluent/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: docker.confluent.io:5000/confluent/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"


